# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 00:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0002_auto_20170710_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walmartmodel',
            name='largeImage',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='walmartmodel',
            name='name',
            field=models.FileField(upload_to=''),
        ),
    ]
