# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0004_auto_20170710_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walmartmodel',
            name='modelNumber',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='walmartmodel',
            name='name',
            field=models.FileField(upload_to=''),
        ),
    ]
