# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0007_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='key',
            field=models.CharField(max_length=100),
        ),
    ]
