# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 12:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0008_auto_20170710_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walmartmodel',
            name='date_modified',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 10, 12, 34, 5, 903790, tzinfo=utc)),
        ),
    ]
