# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0009_auto_20170710_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walmartmodel',
            name='date_modified',
            field=models.DateTimeField(),
        ),
    ]
